### PR TITLE
Adding chmod+x

### PR DESCRIPTION
**Pull request by AceHack**
copilot:all

### CODE REVIEW

**Comment by AceHack** [comment]
Hey, I got my CLA setup using:
https://github.com/microsoft/ContributorLicenseAgreement
see https://github.com/AlephZ-ai/ContributorLicenseAgreement

**Review by AceHack — COMMENTED** [review]
wtf

**Comment by nanis94** [comment]
alephz-ai:main

**Review by nanis94 — APPROVED** [review]
alephz-ai:main

**Review by nanis94 — COMMENTED** [review]
master

**Pull request closed without merging**
